import { Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import Link from 'next/link'

const translations: Record<string, {
  badge: string, h1a: string, h1b: string, h1c: string,
  desc: string, cta: string, demo: string, fine: string,
  howTitle: string, howSub: string, whyTitle: string,
  step1: string, step2: string, step3: string, step4: string, step5: string,
  s1d: string, s2d: string, s3d: string, s4d: string, s5d: string,
  f1: string, f2: string, f3: string, f4: string, f5: string, f6: string,
  f1d: string, f2d: string, f3d: string, f4d: string, f5d: string, f6d: string,
  pricing: string, footer: string
}> = {
  en: {
    badge: '🌍 Now supporting 50+ languages',
    h1a: 'Your voice.', h1b: 'Every language.', h1c: 'Zero effort.',
    desc: 'PolyCast uses AI to transcribe, translate, and dub your YouTube videos in your own cloned voice — automatically uploaded back to your channel in every language you choose.',
    cta: 'Start dubbing for free', demo: 'Watch a demo', fine: 'No credit card required · Free to start · Cancel anytime',
    howTitle: 'How PolyCast works', howSub: 'From one video to a global audience in minutes',
    whyTitle: 'Why creators choose PolyCast',
    step1: 'Upload your video', step2: 'AI transcribes it', step3: 'DeepL translates', step4: 'Your voice, dubbed', step5: 'Auto-uploaded',
    s1d: 'Connect your YouTube channel and select any video you want to translate.',
    s2d: 'Whisper AI converts your speech to text with near-perfect accuracy in 99 languages.',
    s3d: 'Your transcript is translated into up to 50 languages with natural phrasing.',
    s4d: 'ElevenLabs clones your voice and speaks the translation — it sounds like you.',
    s5d: 'The dubbed video is automatically uploaded to your YouTube channel.',
    f1: 'Voice cloning', f2: 'Fully automated', f3: '50+ languages', f4: 'Growth analytics', f5: 'You own your voice', f6: 'Grow your revenue',
    f1d: 'Your audience hears you — not a robot. PolyCast clones your exact voice, tone, and personality.',
    f2d: 'Upload once, get dubbed videos in every language automatically uploaded to your channel.',
    f3d: 'Reach Arabic, Hindi, Chinese, Korean, Japanese, Spanish speakers — and 45 more markets.',
    f4d: 'See exactly which languages are driving new subscribers and watch time across every market.',
    f5d: 'Your voice model belongs to you. Enable or disable languages anytime. Delete anytime.',
    f6d: 'More views in more markets means more ad revenue, sponsorships, and subscribers — on autopilot.',
    pricing: 'Pricing', footer: '© 2026 PolyCast. Built for creators, by creators.'
  },
  ar: {
    badge: '🌍 يدعم الآن أكثر من 50 لغة',
    h1a: 'صوتك.', h1b: 'كل لغة.', h1c: 'بلا جهد.',
    desc: 'تستخدم PolyCast الذكاء الاصطناعي لنسخ مقاطع YouTube وترجمتها ومضاعفتها بصوتك المستنسخ — يتم رفعها تلقائياً إلى قناتك بكل لغة تختارها.',
    cta: 'ابدأ مجاناً', demo: 'شاهد عرضاً', fine: 'لا تحتاج بطاقة ائتمانية · مجاني للبدء · إلغاء في أي وقت',
    howTitle: 'كيف تعمل PolyCast', howSub: 'من فيديو واحد إلى جمهور عالمي في دقائق',
    whyTitle: 'لماذا يختار المبدعون PolyCast',
    step1: 'ارفع الفيديو', step2: 'يفسّر الذكاء الاصطناعي', step3: 'ترجمة DeepL', step4: 'صوتك المدبلج', step5: 'رفع تلقائي',
    s1d: 'اربط قناتك على يوتيوب واختر أي فيديو تريد ترجمته.',
    s2d: 'يحوّل Whisper AI كلامك إلى نص بدقة شبه مثالية في 99 لغة.',
    s3d: 'تتم ترجمة النص إلى ما يصل إلى 50 لغة بعبارات طبيعية.',
    s4d: 'تستنسخ ElevenLabs صوتك وتتحدث بالترجمة — يبدو وكأنك أنت.',
    s5d: 'يتم رفع الفيديو المدبلج تلقائياً إلى قناتك على يوتيوب.',
    f1: 'استنساخ الصوت', f2: 'مؤتمت بالكامل', f3: 'أكثر من 50 لغة', f4: 'تحليلات النمو', f5: 'صوتك ملكك', f6: 'زِد دخلك',
    f1d: 'يسمع جمهورك صوتك — لا روبوت. تستنسخ PolyCast صوتك ونبرتك وشخصيتك.',
    f2d: 'ارفع مرة واحدة، واحصل على مقاطع مدبلجة بكل لغة مرفوعة تلقائياً.',
    f3d: 'تواصل مع المتحدثين بالعربية والهندية والصينية والكورية واليابانية والإسبانية.',
    f4d: 'اعرف بالضبط أي اللغات تجلب مشتركين جدداً.',
    f5d: 'نموذج صوتك ملكك. فعّل أو عطّل اللغات في أي وقت.',
    f6d: 'المزيد من المشاهدات يعني المزيد من الإيرادات والمشتركين — تلقائياً.',
    pricing: 'الأسعار', footer: '© 2026 PolyCast. مصنوع للمبدعين، من قِبل المبدعين.'
  },
  zh: {
    badge: '🌍 现已支持50多种语言',
    h1a: '您的声音。', h1b: '每种语言。', h1c: '零努力。',
    desc: 'PolyCast 使用人工智能转录、翻译和配音您的 YouTube 视频，使用您自己克隆的声音——自动上传回您的频道，支持您选择的每种语言。',
    cta: '免费开始配音', demo: '观看演示', fine: '无需信用卡 · 免费开始 · 随时取消',
    howTitle: 'PolyCast 如何工作', howSub: '几分钟内从一个视频到全球观众',
    whyTitle: '创作者为何选择 PolyCast',
    step1: '上传视频', step2: 'AI 转录', step3: 'DeepL 翻译', step4: '您的声音配音', step5: '自动上传',
    s1d: '连接您的 YouTube 频道并选择您想翻译的任何视频。',
    s2d: 'Whisper AI 以近乎完美的准确度将您的语音转换为99种语言的文字。',
    s3d: '您的文字稿被翻译成多达50种语言，措辞自然。',
    s4d: 'ElevenLabs 克隆您的声音并朗读翻译——听起来就像您在说话。',
    s5d: '配音视频自动上传回您的 YouTube 频道。',
    f1: '声音克隆', f2: '全自动化', f3: '50多种语言', f4: '增长分析', f5: '您拥有自己的声音', f6: '增加收入',
    f1d: '您的观众听到的是您的声音——而不是机器人。PolyCast 克隆您的声音、语调和个性。',
    f2d: '上传一次，获得每种语言的配音视频，自动上传到您的频道。',
    f3d: '接触阿拉伯语、印地语、中文、韩语、日语、西班牙语使用者。',
    f4d: '准确了解哪些语言正在带来新订阅者和观看时间。',
    f5d: '您的声音模型属于您。随时启用或禁用语言。随时删除。',
    f6d: '更多市场的更多观看意味着更多广告收入、赞助和订阅者——自动完成。',
    pricing: '价格', footer: '© 2026 PolyCast. 为创作者打造，由创作者打造。'
  },
  hi: {
    badge: '🌍 अब 50+ भाषाओं का समर्थन',
    h1a: 'आपकी आवाज़।', h1b: 'हर भाषा।', h1c: 'बिना किसी प्रयास के।',
    desc: 'PolyCast AI का उपयोग करके आपके YouTube वीडियो को आपकी खुद की क्लोन की गई आवाज़ में ट्रांसक्राइब, अनुवाद और डब करता है — आपके चैनल पर हर चुनी गई भाषा में स्वचालित रूप से अपलोड किया जाता है।',
    cta: 'मुफ्त में डबिंग शुरू करें', demo: 'डेमो देखें', fine: 'क्रेडिट कार्ड की जरूरत नहीं · मुफ्त में शुरू · कभी भी रद्द करें',
    howTitle: 'PolyCast कैसे काम करता है', howSub: 'एक वीडियो से मिनटों में वैश्विक दर्शक',
    whyTitle: 'क्रिएटर्स PolyCast क्यों चुनते हैं',
    step1: 'वीडियो अपलोड करें', step2: 'AI ट्रांसक्राइब करता है', step3: 'DeepL अनुवाद', step4: 'आपकी आवाज़, डब', step5: 'स्वचालित अपलोड',
    s1d: 'अपना YouTube चैनल कनेक्ट करें और कोई भी वीडियो चुनें जिसे आप अनुवाद करना चाहते हैं।',
    s2d: 'Whisper AI 99 भाषाओं में लगभग परफेक्ट सटीकता के साथ आपकी बोली को टेक्स्ट में बदलता है।',
    s3d: 'आपके ट्रांसक्रिप्ट का 50 भाषाओं में प्राकृतिक वाक्यांशों के साथ अनुवाद किया जाता है।',
    s4d: 'ElevenLabs आपकी आवाज़ क्लोन करता है और अनुवाद बोलता है — यह आप जैसा लगता है।',
    s5d: 'डब किया गया वीडियो स्वचालित रूप से आपके YouTube चैनल पर अपलोड हो जाता है।',
    f1: 'आवाज़ क्लोनिंग', f2: 'पूरी तरह स्वचालित',
